project:
  type: website
  output-dir: _site

resources:
  - CNAME
  
execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: assets/css/styles.css
    toc: true
  
website:
  title: "Essay"
  favicon: assets/favicons/favicon.png
  repo-url: https://github.com/zag13/essay
  navbar:
    left:
      - text: Algorithm
        href: docs/algorithm/index.qmd
      - text: Language
        href: docs/language/index.qmd
      - text: Data System
        href: docs/data-system/index.qmd
      - text: Technology Stack
        menu:
         - text: "UNIX"
           href: docs/unix/index.qmd
           
  sidebar:
    - id: language
      title: "Language"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "Language"
          href: docs/language/index.qmd
          contents:
            - section: "Go"
              href: docs/language/go/index.qmd
              contents: 
                - docs/language/go/100go.qmd
            - section: "Rust"
              href: docs/language/rust/index.qmd
              contents: 
            - section: "JavaScript"
              href: docs/language/javascript/index.qmd
              contents:
    - id: data-system
      title: "Data System"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "Data System"
          href: docs/data-system/index.qmd
          contents:
          - section: "DataBase"
            href: docs/data-system/database/index.qmd
            contents: 
              - docs/data-system/database/distributed-transaction.qmd
          - section: "MySQL"
            href: docs/data-system/mysql/index.qmd
            contents: 